version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    container_name: smg-horizon
    restart: always
    build: .
    ports:
      - '3001:3001'
    environment:
      - REDIS_HOST=redis
    links:
      - redis
